global proc float Add(float $input[])
{
    // plain and simple, take one input and add it to the next and accumulate
    $sum = 0;
    for($i = 0; $i < size($input); $i++)
    {
        $sum += $input[$i];
    }
    return($sum);
}
global proc float Subtract(float $input[])
{
    /* In order to get the correct answer the sum needs
    to be equal to the first number in the array */
    float $sum = $input[0];
    // loop to subtract
    for($i = 1; $i < size($input); $i++)
    {
        $sum -= $input[$i];
    }
    return($sum);
}
global proc float Multiply(float $input[])
{
    float $product = $input[0];
    // Loop through and multiply by first input and second and so on...
    for($i = 1; $i < size($input); $i++)
    {
        $product *= $input[$i];
    }
    return($product);
}
global proc float Divide(float $input[])
{
    float $dividend = $input[0];
    for($i = 1; $i < size($input); $i++)
    {
        // Make sure that after the first input there are no divide by zero errors
        if ($input[$i] == 0)
        {
            print("One or more input creates division by zero.");
            break;
        }
        // Loop through and divide the first input by second and so on...
        $dividend /= $input[$i];
    }
    return($dividend);
}
global proc float Power(float $input[])
{
    // Takes base and exponent and returns a power
    float $base = $input[0];
    float $exponent = $input[1];
    float $power = pow($base, $exponent);
    return($power);
}

global proc float Mean(float $input[])
{
    // create variable to keep track of input
    float $total = 0;
    // add all input together
    for($i = 0; $i < size($input); $i++)
    {
        $total += $input[$i];
    }
    // return the sum of input divided by number of data
    return($total/size($input));
}

global proc float Median(float $input[])
{
    // take the input and sort it
    float $sortedinput[] = `sort $input`;
    float $median;
    /* if the input has an even number of data
    then take the average of the two middle numbers*/
    if(size($input) % 2 == 0)
    {
        $median = (($input[size($input)/2] + $input[(size($input)/2)-1])/2);
    }
    // Otherwise just take the number in the middle
    else
    {
        $median = $input[((size($input)/2))];
    }
    return($median);
}

global proc Calculator(string $operation, float $input[])
{
    // create variables to display results
    float $result = 0;
    string $usedOperator = "";
    string $finalResult = "";

    // chain of if statements to decide which operation is to be performed
    if($operation == "+" || $operation == "add" || $operation == "1")
    {
        $result = `Add($input)`;
        $usedOperator = "+";
    }
    else if($operation == "-" || $operation == "subtract" || $operation == "2")
    {
        $result = `Subtract($input)`;
        $usedOperator = "-";
    }
    else if($operation == "*" || $operation == "x" || $operation == "multiply" || $operation == "3")
    {
        $result = `Multiply($input)`;
        $usedOperator = "*";
    }
    else if($operation == "/" || $operation == "divide" || $operation == "4")
    {
        $result = `Divide($input)`;
        $usedOperator = "/";
    }
    else if($operation == "^" || $operation == "power" || $operation == "5")
    {
        $result = `Power($input)`;
        $usedOperator = "^";
    }
    else if($operation == "mean" || $operation == "average" || $operation == "6")
    {
        $result = `Mean($input)`;
        $usedOperator = ",";
        $finalResult = "The mean of ";
    }
    else if($operation == "median" || $operation == "7")
    {
        $result = `Median($input)`;
        $usedOperator = ",";
        $finalResult = "The median of ";
    }

    // print statement to print the results to the console
    $finalResult += ($input[0] + " ");
    for ($i=1; $i<size($input); $i++)
    {
        $finalResult += ($usedOperator +  " " + $input[$i] + " ");
    }
    $finalResult += ("= " + $result);
    string $resultTxtField = `optionVar -q "resultText"`;
    textField -e -text $finalResult $resultTxtField;
}

global proc Input()
{
    string $dataField = `optionVar -q "dataList"`;
    string $input = `textField -q -text $dataField`;
    string $inputList[];
    tokenize $input "," $inputList;
    float $floatList[];
    for($i=0;$i<size($inputList);$i++)
    {
        $floatList[size($floatList)] = float($inputList[$i]);
    }

    string $selectedButton = `radioCollection -q -select radioOp`;

    Calculator($selectedButton, $floatList);
}

// Procedure to create the user interface for the script
global proc UserInterface()
{
    string $mWindow = "Calculator_UI";
    // Check if the window already exists; if it does, delete it
    if (`window -ex $mWindow`)
    {
        deleteUI $mWindow;
    }

    // Create a new window with a title, size, and adjustable size properties
    $mWindow = `window -title "Calculator"
                              -sizeable 0
                              -width 300
                              -height 400
                              $mWindow`;

    // Create a column layout to hold the UI elements
    string $mColumn = `columnLayout -rs 10 -adjustableColumn 1 -parent $mWindow`;

    // Add some instructional text
    text -parent $mColumn "Enter a comma seperated list of numbers, then select operation.";

    // Create rows for user input fields
    string $firRow = `rowLayout -numberOfColumns 2 -adjustableColumn 2 -parent $mColumn`;
    string $secRow = `rowLayout -numberOfColumns 8 -parent $mColumn`;

    // Add input fields for X min and max values
    text -parent $firRow "List of data:";
    optionVar -stringValue "dataList" `textField -pht "1,2,3,4,5..." -parent $firRow`;

    text -parent $secRow "Operation:";
    radioCollection -parent $secRow radioOp;
    radioButton -parent $secRow -label "+" add;
    radioButton -parent $secRow -label "-" subtract;
    radioButton -parent $secRow -label "*" multiply;
    radioButton -parent $secRow -label "/" divide;
    radioButton -parent $secRow -label "^" power;
    radioButton -parent $secRow -label "Mean" mean;
    radioButton -parent $secRow -label "Median" median;
    radioCollection -e -select add radioOp;
    // Add a button that runs the RandomPlacement procedure when clicked
    button -parent $mColumn -label "Go!" -command "Input";
    optionVar -stringValue "resultText" `textField -ed 0 -parent $mColumn "e"`;

    // Display the window
    showWindow;
}

// Call the UserInterface procedure to create and display the UI when the script runs
UserInterface();